name: testapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_analytics: ^11.2.0
  permission_handler: ^11.3.1
  mobile_scanner: ^5.2.1
  cunning_document_scanner: ^1.2.3
  camera: ^0.11.0+2
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true
  assets:
  - assets/